services:
  app:
    restart: always
    platform: linux/x86_64
    image: solidtime/solidtime:latest
    user: "1000:1000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${REVERSE_PROXY_NETWORK}"
      - "traefik.http.services.solidtime.loadbalancer.server.port=8000"
      # http
      - "traefik.http.routers.solidtime.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.solidtime.entrypoints=web"
      - "traefik.http.routers.solidtime.middlewares=redirect-to-https@file"
      # https
      - "traefik.http.routers.solidtime-https.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.solidtime-https.entrypoints=websecure"
      - "traefik.http.routers.solidtime-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.solidtime-https.tls=true"
    networks:
      - frontend
      - internal
    volumes:
      - "app-storage:/var/www/html/storage"
      - "./logs:/var/www/html/storage/logs"
      - "./app-storage:/var/www/html/storage/app"
    environment:
      CONTAINER_MODE: http
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health-check/up || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    env_file:
      - laravel.env
    depends_on:
      - database
  scheduler:
    restart: always
    platform: linux/x86_64
    image: solidtime/solidtime:latest
    networks:
      - internal
    volumes:
      - "app-storage:/var/www/html/storage"
      - "./logs:/var/www/html/storage/logs"
      - "./app-storage:/var/www/html/storage/app"
    environment:
      CONTAINER_MODE: scheduler
    env_file:
      - laravel.env
    depends_on:
      - database
  queue:
    restart: always
    platform: linux/x86_64
    image: solidtime/solidtime:latest
    user: "1000:1000"
    networks:
      - internal
    volumes:
      - "app-storage:/var/www/html/storage"
      - "./logs:/var/www/html/storage/logs"
      - "./app-storage:/var/www/html/storage/app"
    environment:
      CONTAINER_MODE: worker
      WORKER_COMMAND: "php /var/www/html/artisan queue:work"
    env_file:
      - laravel.env
    depends_on:
      - database
  database:
    image: 'postgres:15'
#    ports:
#      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'database-storage:/var/lib/postgresql/data'
    networks:
      - internal
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
networks:
  frontend:
    name: ${REVERSE_PROXY_NETWORK}
    external: true
  internal:
volumes:
  database-storage:
  app-storage:
